### ISSUE TITLE
hard drive not being detected

### ISSUE THREAD

**Issue by bornikfik** [MishaProductions/Misha-OS#20]
#### Bug Report  
  
- What were you doing when you encountered the bug?  
installing the os

- How can the bug be reproduced?
idk

- What should happen instead of the bug?  
the hard drive should be detected
  
- What happens unexpectedly?  
the hard drive doesnt get detected

image:
![image](https://user-images.githubusercontent.com/79079570/193475490-fb36daa5-8d8d-49a8-8902-c7cb06be0fb9.png)

**Comment by MishaTY** [comment]
hi, i want to rewrite mishaos to fix all of these bugs due to an outdated version of Cosmos that didn't have my disk manager rewrite. I will fix this when I rewrite MishaOS.

**Comment by bornikfik** [comment]
ok thanks
